### ISSUE TITLE
Connection issues with the Mastodon iOS App

### ISSUE THREAD

**Issue by tomfinitely** [akirk/enable-mastodon-apps#12]
Mirror of #11 but for Mastodon app.

Per @akirk: Let's use this issue for debugging.

Helpful for debugging would be:

    Please use the latest version from this repo.
    Take a look at access and error logs of your webserver. Which requests does Ivory make?

**Comment by akirk** [comment]
I think those access logs are unrelated and look more like someone scanning your blog.

Could you check if 0.3.0 makes the app work now? Thank you!

**Comment by andreasjr** [comment]
I can provide logs if needed, but when I try to log in with the Mastodon iOS app, it will recognize the server, authenticate me, and then leave me on the "Enter URL" screen with no error but also no success.

**Comment by electricbrick** [comment]
@akirk Still no joy. I've attempted to log in to your server late last night (around midnight US East Coast time, ~9 hours ago) to hopefully leave you a breadcrumb trail.

**Comment by akirk** [comment]
@electricbrick Thank you and sorry but if you have time could you do it again? I had disabled the logging, it's now back in place. Thank you very much!

**Comment by electricbrick** [comment]
@akirk done!

**Comment by akirk** [comment]
I hope [the fix for Ivory](https://github.com/akirk/enable-mastodon-apps/issues/11#issuecomment-1520318056) has also made this one work. Please try 0.3.2.

**Comment by huckabarry** [comment]
I've only been able to get Ivory to semi-work, Ice Cubes and Mastodon official app continue to log auths in the plugin but will not actually pass OAUTH on the login and add the account to the app.

**Comment by electricbrick** [comment]
Running EMA 0.3.2 Mastodon is still returning an error message for me.

![image](https://user-images.githubusercontent.com/2481417/234422527-dca095d6-2ba1-4f4a-843b-f5d583760641.png)

**Comment by huckabarry** [comment]
> Running EMA 0.3.2 Mastodon is still returning an error message for me.
> 
> ![image](https://user-images.githubusercontent.com/2481417/234422527-dca095d6-2ba1-4f4a-843b-f5d583760641.png)

That happened to me when I mistakenly tried "registering" with my own server when I needed to click the login button instead.

**Comment by akirk** [comment]
Right, please make sure to click "Log In" and not "Pick my own Server"
<img width="439" alt="Screenshot 2023-04-26 at 20 56 55" src="https://user-images.githubusercontent.com/203408/234675751-f175757b-871d-45cc-94a0-0647cf5ed2f1.png">

Alas, the login doesn't work yet but at least I can test it so I hope I can get it to work soon!

**Comment by akirk** [comment]
I have released 0.3.3 with some more fixes of the Mastodon iOS app, please test again, I hope it now works better!

**Comment by electricbrick** [comment]
Hate reporting the bad news @akirk, but Mastodon Official for iOS is still not working for me, as of 0.3.4

**Comment by akirk** [comment]
@electricbrick what happens? Is there an error message? Are you using the Login button for sure and and not "Pick a server"?

**Comment by huckabarry** [comment]
> @electricbrick what happens? Is there an error message? Are you using the Login button for sure and and not "Pick a server"? 

It's working for me. It wasn't working at all yesterday, but today it's working better than any other client.

**Comment by electricbrick** [comment]
@akirk apologies, it was late and I was bleary-eyed, missing that instruction above. Login DOES work.

**Comment by huckabarry** [comment]
Back to not working today. None of the apps. I can post but can't see a timeline again. Ivory keeps crashing.

**Comment by akirk** [comment]
There must be something off with the JSON format. Could you download the JSON and put it somewhere (privately if you prefer?) accessible? Are you comfortable with the command line? You need to get an access token from the admin page like so

![ScreenFlow](https://user-images.githubusercontent.com/203408/235289875-6f364395-2632-46cf-9e6a-1cb1d7cbbe64.gif)

and then get the JSON like this (put your token where the 1234 is)
```
curl -H"Authorization: Bearer 1234" https://yourdomain/api/v1/timelines/home
```

**Comment by huckabarry** [comment]
> There must be something off with the JSON format. Could you download the JSON and put it somewhere (privately if you prefer?) accessible? Are you comfortable with the command line? You need to get an access token from the admin page like so
> 
> 
> 
> ![ScreenFlow](https://user-images.githubusercontent.com/203408/235289875-6f364395-2632-46cf-9e6a-1cb1d7cbbe64.gif)
> 
> 
> 
> and then get the JSON like this (put your token where the 1234 is)
> 
> ```
> 
> curl -H"Authorization: Bearer 1234" https://yourdomain/api/v1/timelines/home
> 
> ```
> 
> 

Oh man, I just went down some rabbit holes trying to figure that out. Setting up a user with access on the server and such. Definitely out of my depth. I'll have to look at it more closely tomorrow.

**Comment by akirk** [comment]
You don't need that, you can just use the same token as your app.

**Comment by huckabarry** [comment]
> You don't need that, you can just use the same token as your app. 

Oh, I see what you're saying now. Here's the JSON file. I'm user "bryan@inthedeltawaves.social". Let me know if you see anything out of the ordinary.

https://drive.google.com/file/d/1LrtL6RhkgUnxQmzfmtlUHemKwoar9TW4/view?usp=sharing

**Comment by akirk** [comment]
I wasn't able to find anything but maybe at the time it was working again? I have added a new debug mode in #23 which should make it easier to get up to date JSON files in case apps crash or timelines are empty.

@huckabarry is it working for you at the moment or is it broken?
