### ISSUE TITLE
Follow Request in Mona on IOS

### ISSUE THREAD

**Issue by soehlschlaeger** [akirk/enable-mastodon-apps#36]
Hello Alex,

still a great work. 

When trying to follow someone in Mona for IOS, I get an error message. However, the followed person appears in the Friends plugin on Wordpress. I also can't see the user's posts and followers in profile view.

In general, I only see my posts and the replies to them in timeline.

**Comment by akirk** [comment]
Thanks for reporting! This was a bug in the Friends plugin, it should be fixed with [2.7.5](https://github.com/akirk/friends/releases/tag/2.7.5).

**Comment by soehlschlaeger** [comment]
> Thanks for reporting! This was a bug in the Friends plugin, it should be fixed with [2.7.5](https://github.com/akirk/friends/releases/tag/2.7.5).

Oh okay. Thanks for that.

**Comment by soehlschlaeger** [comment]
I've testet it with icecubes an Mona. In Mona for IOS it is still broken. In icecubes works it. ![image](https://github.com/akirk/enable-mastodon-apps/assets/58472193/301448f1-f7cd-4316-ba4b-cd7c4f029178)![image](https://github.com/akirk/enable-mastodon-apps/assets/58472193/f90e99d0-a045-4249-b09b-13ed2e4436ed)

**Comment by soehlschlaeger** [comment]
In icecubes there only a few posts. They are repeating several times.
